/**
 * Loads the telemetry history recorded by the PHP cron job.
 * The file is at /data/telemetry-history.json, generated by
 * cron/record-telemetry.php every 60s during the live mission.
 *
 * After the mission ends, this file becomes the permanent archive
 * for playback and Mission Profile chart.
 */

import type { SpacecraftState } from "../targets/types";

interface CompactRecord {
  t: number;          // epoch ms
  p: [number, number, number]; // position km
  v: [number, number, number]; // velocity km/s
  de: number;         // distance from Earth km
  dm: number;         // distance from Moon km
  s: number;          // speed km/s
}

export async function fetchTelemetryHistory(
  signal?: AbortSignal,
): Promise<SpacecraftState[]> {
  const url = `/data/telemetry-history.json?_=${Date.now()}`; // cache bust
  const resp = await fetch(url, { signal });
  if (!resp.ok) return []; // file doesn't exist yet — not an error

  const records = (await resp.json()) as CompactRecord[];

  return records.map((r) => ({
    timestamp: new Date(r.t),
    positionKm: r.p,
    velocityKmS: r.v,
    distanceFromEarthKm: r.de,
    distanceFromMoonKm: r.dm,
    speedKmS: r.s,
  }));
}
